# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "pins-r")
v <- vetiver_pin_read(b, "penguins_model", version = "20241113T102340Z-ea18a")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
